In [15]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\rames\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: openpyxl in c:\users\rames\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rames\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rames\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\rames\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\rames\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: et_xmlfile in c:\users\rames\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\rames\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [29]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\rames\anaconda3\lib\site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (1.11.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (2.0.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (3.7.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\rames\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.2.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rames\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rames\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\rames\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rames\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\rames\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd

In [31]:
file_path="D:\\Datascience\\Online_retail.xlsx"

In [32]:
df = pd.read_excel(file_path)
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [33]:
#checking for null values
df.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [34]:
#datatypes
df.dtypes

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    object
dtype: object

In [35]:
#general information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [42]:
#removing duplicates
df1=df.drop_duplicates()

In [44]:
#verifying the dataset
df1.isnull()

      shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
7492                                              False
7493                                              False
7495                                              False
7496                                              False
7499                                              False

[5175 rows x 1 columns]

In [46]:
#applying one-hot encoding to balance
one_hot_encoded = df1['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'].str.get_dummies(',')
one_hot_encoded

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7493,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
7495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [47]:
#Applying apriori algorithm
frequent_itemsets = apriori(one_hot_encoded, min_support=0.05, use_colnames=True)
frequent_itemsets

C:\Users\rames\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                            itemsets
0   0.113816                           (burgers)
1   0.103575                              (cake)
2   0.054879                         (champagne)
3   0.083865                           (chicken)
4   0.205217                         (chocolate)
5   0.060676                           (cookies)
6   0.071884                       (cooking oil)
7   0.208116                              (eggs)
8   0.083865                          (escalope)
9   0.192657                      (french fries)
10  0.059324                       (fresh bread)
11  0.084638                   (frozen smoothie)
12  0.129855                 (frozen vegetables)
13  0.070145                     (grated cheese)
14  0.169082                         (green tea)
15  0.135845                       (ground beef)
16  0.066473                     (herb & pepper)
17  0.065121                             (honey)
18  0.094879                    (low fat yogurt)
19  0.170048                              (milk)
20  0.299710                     (mineral water)
21  0.087536                         (olive oil)
22  0.125217                          (pancakes)
23  0.057391                            (salmon)
24  0.098744                            (shrimp)
25  0.070918                              (soup)
26  0.229565                         (spaghetti)
27  0.091981                          (tomatoes)
28  0.083285                            (turkey)
29  0.077874                  (whole wheat rice)
30  0.073237          (chocolate, mineral water)
31  0.055845              (spaghetti, chocolate)
32  0.070145               (eggs, mineral water)
33  0.051401                   (eggs, spaghetti)
34  0.050435  (frozen vegetables, mineral water)
35  0.058744        (ground beef, mineral water)
36  0.055845            (spaghetti, ground beef)
37  0.067826               (milk, mineral water)
38  0.050048                   (milk, spaghetti)
39  0.085024          (spaghetti, mineral water)

In [50]:
#applying association rules
from mlxtend.frequent_patterns import apriori, association_rules

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(chocolate),(mineral water),0.205217,0.299710,0.073237,0.356874,1.190730,0.011731,1.088884,0.201538
1,(mineral water),(chocolate),0.299710,0.205217,0.073237,0.244358,1.190730,0.011731,1.051798,0.228732
2,(spaghetti),(chocolate),0.229565,0.205217,0.055845,0.243266,1.185406,0.008735,1.050280,0.203012
3,(chocolate),(spaghetti),0.205217,0.229565,0.055845,0.272128,1.185406,0.008735,1.058476,0.196793
4,(eggs),(mineral water),0.208116,0.299710,0.070145,0.337047,1.124578,0.007770,1.056320,0.139891
5,(mineral water),(eggs),0.299710,0.208116,0.070145,0.234043,1.124578,0.007770,1.033849,0.158188
6,(eggs),(spaghetti),0.208116,0.229565,0.051401,0.246982,1.075870,0.003625,1.023130,0.089053
7,(spaghetti),(eggs),0.229565,0.208116,0.051401,0.223906,1.075870,0.003625,1.020345,0.091532
8,(frozen vegetables),(mineral water),0.129855,0.299710,0.050435,0.388393,1.295895,0.011516,1.144999,0.262407
9,(mineral water),(frozen vegetables),0.299710,0.129855,0.050435,0.168279,1.295895,0.011516,1.046198,0.326054
10,(ground beef),(mineral water),0.135845,0.299710,0.058744,0.432432,1.442835,0.018030,1.233844,0.355168
11,(mineral water),(ground beef),0.299710,0.135845,0.058744,0.196003,1.442835,0.018030,1.074823,0.438276
12,(spaghetti),(ground beef),0.229565,0.135845,0.055845,0.243266,1.790756,0.024660,1.141953,0.573153
13,(ground beef),(spaghetti),0.135845,0.229565,0.055845,0.411095,1.790756,0.024660,1.308250,0.510993
14,(milk),(mineral water),0.170048,0.299710,0.067826,0.398864,1.330831,0.016861,1.164943,0.299523
15,(mineral water),(milk),0.299710,0.170048,0.067826,0.226306,1.330831,0.016861,1.072713,0.354982
16,(milk),(spaghetti),0.170048,0.229565,0.050048,0.294318,1.282068,0.011011,1.091759,0.265088
17,(spaghetti),(milk),0.229565,0.170048,0.050048,0.218013,1.282068,0.011011,1.061338,0.285566
18,(spaghetti),(mineral water),0.229565,0.299710,0.085024,0.370370,1.235762,0.016221,1.112225,0.247630
19,(mineral water),(spaghetti),0.299710,0.229565,0.085024,0.283688,1.235762,0.016221,1.075557,0.272434

In [51]:
print("Frequent Itemsets:")
print(frequent_itemsets)

Frequent Itemsets:
     support                            itemsets
0   0.113816                           (burgers)
1   0.103575                              (cake)
2   0.054879                         (champagne)
3   0.083865                           (chicken)
4   0.205217                         (chocolate)
5   0.060676                           (cookies)
6   0.071884                       (cooking oil)
7   0.208116                              (eggs)
8   0.083865                          (escalope)
9   0.192657                      (french fries)
10  0.059324                       (fresh bread)
11  0.084638                   (frozen smoothie)
12  0.129855                 (frozen vegetables)
13  0.070145                     (grated cheese)
14  0.169082                         (green tea)
15  0.135845                       (ground beef)
16  0.066473                     (herb & pepper)
17  0.065121                             (honey)
18  0.094879                    (low fat yogurt)
19  0.170048                              (milk)
20  0.299710                     (mineral water)
21  0.087536                         (olive oil)
22  0.125217                          (pancakes)
23  0.057391                            (salmon)
24  0.098744                            (shrimp)
25  0.070918                              (soup)
26  0.229565                         (spaghetti)
27  0.091981                          (tomatoes)
28  0.083285                            (turkey)
29  0.077874                  (whole wheat rice)
30  0.073237          (chocolate, mineral water)
31  0.055845              (spaghetti, chocolate)
32  0.070145               (eggs, mineral water)
33  0.051401                   (eggs, spaghetti)
34  0.050435  (frozen vegetables, mineral water)
35  0.058744        (ground beef, mineral water)
36  0.055845            (spaghetti, ground beef)
37  0.067826               (milk, mineral water)
38  0.050048                   (milk, spaghetti)
39  0.085024          (spaghetti, mineral water)

In [52]:
print("\nAssociation Rules:")
print(rules)

Association Rules:
            antecedents          consequents  antecedent support  \
0           (chocolate)      (mineral water)            0.205217
1       (mineral water)          (chocolate)            0.299710
2           (spaghetti)          (chocolate)            0.229565
3           (chocolate)          (spaghetti)            0.205217
4                (eggs)      (mineral water)            0.208116
5       (mineral water)               (eggs)            0.299710
6                (eggs)          (spaghetti)            0.208116
7           (spaghetti)               (eggs)            0.229565
8   (frozen vegetables)      (mineral water)            0.129855
9       (mineral water)  (frozen vegetables)            0.299710
10        (ground beef)      (mineral water)            0.135845
11      (mineral water)        (ground beef)            0.299710
12          (spaghetti)        (ground beef)            0.229565
13        (ground beef)          (spaghetti)            0.135845
14               (milk)      (mineral water)            0.170048
15      (mineral water)               (milk)            0.299710
16               (milk)          (spaghetti)            0.170048
17          (spaghetti)               (milk)            0.229565
18          (spaghetti)      (mineral water)            0.229565
19      (mineral water)          (spaghetti)            0.299710

    consequent support   support  confidence      lift  leverage  conviction  \
0             0.299710  0.073237    0.356874  1.190730  0.011731    1.088884
1             0.205217  0.073237    0.244358  1.190730  0.011731    1.051798
2             0.205217  0.055845    0.243266  1.185406  0.008735    1.050280
3             0.229565  0.055845    0.272128  1.185406  0.008735    1.058476
4             0.299710  0.070145    0.337047  1.124578  0.007770    1.056320
5             0.208116  0.070145    0.234043  1.124578  0.007770    1.033849
6             0.229565  0.051401    0.246982  1.075870  0.003625    1.023130
7             0.208116  0.051401    0.223906  1.075870  0.003625    1.020345
8             0.299710  0.050435    0.388393  1.295895  0.011516    1.144999
9             0.129855  0.050435    0.168279  1.295895  0.011516    1.046198
10            0.299710  0.058744    0.432432  1.442835  0.018030    1.233844
11            0.135845  0.058744    0.196003  1.442835  0.018030    1.074823
12            0.135845  0.055845    0.243266  1.790756  0.024660    1.141953
13            0.229565  0.055845    0.411095  1.790756  0.024660    1.308250
14            0.299710  0.067826    0.398864  1.330831  0.016861    1.164943
15            0.170048  0.067826    0.226306  1.330831  0.016861    1.072713
16            0.229565  0.050048    0.294318  1.282068  0.011011    1.091759
17            0.170048  0.050048    0.218013  1.282068  0.011011    1.061338
18            0.299710  0.085024    0.370370  1.235762  0.016221    1.112225
19            0.229565  0.085024    0.283688  1.235762  0.016221    1.075557

    zhangs_metric
0        0.201538
1        0.228732
2        0.203012
3        0.196793
4        0.139891
5        0.158188
6        0.089053
7        0.091532
8        0.262407
9        0.326054
10       0.355168
11       0.438276
12       0.573153
13       0.510993
14       0.299523
15       0.354982
16       0.265088
17       0.285566
18       0.247630
19       0.272434

In [54]:
#applying apriori algorithm with a lower support threshold and generating association rules
import warnings
warnings.filterwarnings("ignore")

frequent_itemsets = apriori(one_hot_encoded, min_support=0.02, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

print("Frequent Itemsets:")
print(frequent_itemsets)

Frequent Itemsets:
      support                                 itemsets
0    0.029179                                (almonds)
1    0.045797                                (avocado)
2    0.020483                              (black tea)
3    0.045024                               (brownies)
4    0.113816                                (burgers)
..        ...                                      ...
169  0.020097         (milk, chocolate, mineral water)
170  0.022995    (spaghetti, chocolate, mineral water)
171  0.020676         (eggs, spaghetti, mineral water)
172  0.024734  (spaghetti, ground beef, mineral water)
173  0.022609         (milk, spaghetti, mineral water)

[174 rows x 2 columns]

In [56]:
#applying association rules with lower confidence threshold
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(burgers),(chocolate),0.113816,0.205217,0.024541,0.215620,1.050689,0.001184,1.013262,0.054440
1,(chocolate),(burgers),0.205217,0.113816,0.024541,0.119586,1.050689,0.001184,1.006553,0.060701
2,(burgers),(eggs),0.113816,0.208116,0.036135,0.317487,1.525531,0.012448,1.160248,0.388735
3,(eggs),(burgers),0.208116,0.113816,0.036135,0.173630,1.525531,0.012448,1.072382,0.435026
4,(burgers),(french fries),0.113816,0.192657,0.029372,0.258065,1.339502,0.007444,1.088158,0.286006
...,...,...,...,...,...,...,...,...,...,...
209,(ground beef),"(spaghetti, mineral water)",0.135845,0.085024,0.024734,0.182077,2.141472,0.013184,1.118657,0.616824
210,"(milk, spaghetti)",(mineral water),0.050048,0.299710,0.022609,0.451737,1.507248,0.007609,1.277289,0.354270
211,"(milk, mineral water)",(spaghetti),0.067826,0.229565,0.022609,0.333333,1.452020,0.007038,1.155652,0.333955
212,"(spaghetti, mineral water)",(milk),0.085024,0.170048,0.022609,0.265909,1.563727,0.008150,1.130584,0.394002
213,(milk),"(spaghetti, mineral water)",0.170048,0.085024,0.022609,0.132955,1.563727,0.008150,1.055280,0.434365

In [59]:
print("\nAssociation Rules:")
print(rules)

Association Rules:
                    antecedents                 consequents  \
0                     (burgers)                 (chocolate)
1                   (chocolate)                   (burgers)
2                     (burgers)                      (eggs)
3                        (eggs)                   (burgers)
4                     (burgers)              (french fries)
..                          ...                         ...
209               (ground beef)  (spaghetti, mineral water)
210           (milk, spaghetti)             (mineral water)
211       (milk, mineral water)                 (spaghetti)
212  (spaghetti, mineral water)                      (milk)
213                      (milk)  (spaghetti, mineral water)

     antecedent support  consequent support   support  confidence      lift  \
0              0.113816            0.205217  0.024541    0.215620  1.050689
1              0.205217            0.113816  0.024541    0.119586  1.050689
2              0.113816            0.208116  0.036135    0.317487  1.525531
3              0.208116            0.113816  0.036135    0.173630  1.525531
4              0.113816            0.192657  0.029372    0.258065  1.339502
..                  ...                 ...       ...         ...       ...
209            0.135845            0.085024  0.024734    0.182077  2.141472
210            0.050048            0.299710  0.022609    0.451737  1.507248
211            0.067826            0.229565  0.022609    0.333333  1.452020
212            0.085024            0.170048  0.022609    0.265909  1.563727
213            0.170048            0.085024  0.022609    0.132955  1.563727

     leverage  conviction  zhangs_metric
0    0.001184    1.013262       0.054440
1    0.001184    1.006553       0.060701
2    0.012448    1.160248       0.388735
3    0.012448    1.072382       0.435026
4    0.007444    1.088158       0.286006
..        ...         ...            ...
209  0.013184    1.118657       0.616824
210  0.007609    1.277289       0.354270
211  0.007038    1.155652       0.333955
212  0.008150    1.130584       0.394002
213  0.008150    1.055280       0.434365

[214 rows x 10 columns]

In [60]:
print("Number of generated rules:", len(rules))

Number of generated rules: 214

In [61]:
#converting lift column to numerical datatype
rules['lift'] = pd.to_numeric(rules['lift'])

# Display the top 10 rules with the highest lift
top_rules_lift = rules.nlargest(10, 'lift')
print("\nTop 10 rules with the highest lift:")
print(top_rules_lift)

Top 10 rules with the highest lift:
                      antecedents                   consequents  \
135                 (ground beef)               (herb & pepper)
136               (herb & pepper)                 (ground beef)
206    (spaghetti, mineral water)                 (ground beef)
209                 (ground beef)    (spaghetti, mineral water)
122                    (tomatoes)           (frozen vegetables)
121           (frozen vegetables)                    (tomatoes)
117           (frozen vegetables)                      (shrimp)
118                      (shrimp)           (frozen vegetables)
207  (ground beef, mineral water)                   (spaghetti)
208                   (spaghetti)  (ground beef, mineral water)

     antecedent support  consequent support   support  confidence      lift  \
135            0.135845            0.066473  0.022802    0.167852  2.525100
136            0.066473            0.135845  0.022802    0.343023  2.525100
206            0.085024            0.135845  0.024734    0.290909  2.141472
209            0.135845            0.085024  0.024734    0.182077  2.141472
122            0.091981            0.129855  0.022609    0.245798  1.892867
121            0.129855            0.091981  0.022609    0.174107  1.892867
117            0.129855            0.098744  0.023768    0.183036  1.853640
118            0.098744            0.129855  0.023768    0.240705  1.853640
207            0.058744            0.229565  0.024734    0.421053  1.834131
208            0.229565            0.058744  0.024734    0.107744  1.834131

     leverage  conviction  zhangs_metric
135  0.013772    1.121828       0.698921
136  0.013772    1.315350       0.646983
206  0.013184    1.218680       0.582563
209  0.013184    1.118657       0.616824
122  0.010665    1.153730       0.519483
121  0.010665    1.099440       0.542094
117  0.010946    1.103177       0.529246
118  0.010946    1.145990       0.510977
207  0.011249    1.330751       0.483166
208  0.011249    1.054917       0.590293

In [62]:
#converting confidence to numerical data
rules['confidence'] = pd.to_numeric(rules['confidence'])

# Display the top 10 rules with the highest confidence
top_rules_confidence = rules.nlargest(10, 'confidence')
print("\nTop 10 rules with the highest confidence:")
print(top_rules_confidence)

Top 10 rules with the highest confidence:
                      antecedents      consequents  antecedent support  \
173                        (soup)  (mineral water)            0.070918
210             (milk, spaghetti)  (mineral water)            0.050048
193             (milk, chocolate)  (mineral water)            0.044831
205      (spaghetti, ground beef)  (mineral water)            0.055845
166                   (olive oil)  (mineral water)            0.087536
139                 (ground beef)  (mineral water)            0.135845
207  (ground beef, mineral water)      (spaghetti)            0.058744
197        (chocolate, spaghetti)  (mineral water)            0.055845
146                 (ground beef)      (spaghetti)            0.135845
62                  (cooking oil)  (mineral water)            0.071884

     consequent support   support  confidence      lift  leverage  conviction  \
173            0.299710  0.033430    0.471390  1.572818  0.012175    1.324775
210            0.299710  0.022609    0.451737  1.507248  0.007609    1.277289
193            0.299710  0.020097    0.448276  1.495698  0.006660    1.269275
205            0.299710  0.024734    0.442907  1.477783  0.007997    1.257042
166            0.299710  0.038454    0.439294  1.465728  0.012219    1.248942
139            0.299710  0.058744    0.432432  1.442835  0.018030    1.233844
207            0.229565  0.024734    0.421053  1.834131  0.011249    1.330751
197            0.299710  0.022995    0.411765  1.373876  0.006258    1.190493
146            0.229565  0.055845    0.411095  1.790756  0.024660    1.308250
62             0.299710  0.028986    0.403226  1.345386  0.007441    1.173459

     zhangs_metric
173       0.391998
210       0.354270
193       0.346971
205       0.342434
166       0.348228
139       0.355168
207       0.483166
197       0.288229
146       0.510993
62        0.276602

In [63]:
#rules with lift > 1 and confidence > 0.7
high_confidence_rules = rules[(rules['lift'] > 1) & (rules['confidence'] > 0.7)]
print("\nRules with lift > 1 and confidence > 0.7:")
print(high_confidence_rules)

Rules with lift > 1 and confidence > 0.7:
Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []

In [ ]:
#Lift and importance of lift in association rules

#It is a metric used to mine the relationship between the two items.
#A high lift value indicates that the association rule is more significant as two items are highly dependent on each other.

In [ ]:
#Support : It is a measure of number of times the item set appears in the dataset.
#          Calculated by the number of transactions containing an item set by the total number of transactions.

In [ ]:
#Confidence : It is a measure of likelihood that an itemset will appear if another itemset appears.
#             Calculated by dividing the number of transactions containing both itemsets by number of transactions containing
#             first itemset.

In [ ]:
#Limitations of using association rules :-
#Poor performance
#produces boring rules
#already have many discovered rules
#noise and performance effects
#not suitable for heterogeneous data
#sensitive to thresholds
#generating too many rules for large datasets which makes it messy and hard to find important patterns